#
# See: https://github.com/conda-forge/conda-smithy
# See: https://conda-forge.org/docs/maintainer/conda_forge_yml.html
#
# Remember to setup BINSTAR_TOKEN in:
#   anaconda.org (Settings -> Access)
#   azure (could not make it work setting it in a Library, so just do for the pipeline: pipeline -> Edit -> Variables (make secret))
# Make sure not to leak secrets!
#

build_platform:
  osx_arm64: osx_64

conda_build:
  pkg_format: '2'

conda_forge_output_validation: true

provider:
  linux: azure
  linux_aarch64: azure
  linux_ppc64le: azure
  win: azure
  osx: azure

test: native_and_emulated

channels:
  sources:
    - sdvillal
    - conda-forge
  targets:
    - ["sdvillal", "main"]

github:
  user_or_org: sdvillal
  branch_name: master

azure:
  user_or_org: sdvillal
  upload_packages: True
  force: False
